name: My First Action

on: push  # Runs when code is pushed

jobs:
  my-job: #Here you put the name of the job
    runs-on: ubuntu-latest # The CI-CD pipeline will run on Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # clones the repo
      
      - name: Print Hello World
        run: echo "Hello, GitHub Actions!" # This is just the command

      - name: Ping google
        run: curl -Is https://google.com | head -n 1 # ping google 4 times

      - name: List Directory Contents
        run: ls -la  # Lists all files with detailed info

      - name: Run Time Script
        run: bash IsraeliTime.sh
